# Generated by Django 2.0 on 2021-01-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='census',
            name='type',
            field=models.CharField(choices=[('VB', 'VotacionBinaria'), ('V', 'Votacion'), ('VP', 'VotacionPreferencia'), ('VM', 'VotacionMultiple'), ('Vo', 'Voting')], default='Vo', max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='census',
            unique_together={('voting_id', 'type')},
        ),
    ]
