dist: xenial

services:
  - postgresql
addons:
  postgresql: "9.4"
matrix:
  include:
    - language: python
      python: 
        - "3.6"
      before_install:
        - psql -U postgres -c "DROP DATABASE IF EXISTS test_decide"
        - psql -U postgres -c "create user decide password 'decide'"
        - psql -U postgres -c "create database test_decide owner decide"
        - psql -U postgres -c "ALTER USER decide CREATEDB"
        - psql -U postgres -c "create database decide owner decide"
      install:
        - pip install -r requirements.txt
        - pip install codacy-coverage
      script:
        - cd decide
        - python ./manage.py makemigrations
        - python ./manage.py migrate
        - coverage run --branch --source=. ./manage.py test voting census booth visualizer --keepdb --with-xunit
        - coverage xml
        - python-codacy-coverage -r coverage.xml

    - language: node_js
      node_js:
        - "12"
      before_install:
        - cd decide/booth/decide-react
      install:
        - npm install
        - npm install jest
      script:
        - npm test
        
notifications:
  email: false
deploy:
  provider: heroku
  app: egchueznar
  on:
    branch: releaseM3
  strategy: git
  api_key:
    secure: 1a9370fe-7079-4132-98a0-6a6dab139fd4