# Generated by Django 2.0 on 2021-01-04 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_auto_20210102_1705'),
        ('voting', '0004_auto_20210104_1635'),
    ]

    operations = [
    ]
